apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin-price.name" . }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ include "bitcoin-price.name" . }}
